import type { Metadata } from "next";
import "./globals.css";
import HeroUIThemeProvider from "@/providers/HeroUIThemeProvider";


export const metadata: Metadata = {
  title: "Tabib Online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
        suppressHydrationWarning={true}
      >
        <HeroUIThemeProvider>
          {children}
        </HeroUIThemeProvider>
      </body>
    </html>
  );
}
